//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWEB1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProyectoWebEntities : DbContext
    {
        public dbProyectoWebEntities()
            : base("name=dbProyectoWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArchivoProyecto> tblArchivoProyecto { get; set; }
        public virtual DbSet<tblArchivoProyecto_Materiales> tblArchivoProyecto_Materiales { get; set; }
        public virtual DbSet<tblMateriales> tblMateriales { get; set; }

        public System.Data.Entity.DbSet<ProyectoWEB1.Models.ViewModels.MaterialesViewModel> MaterialesViewModels { get; set; }
    }
}
