//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWEB1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblArchivoProyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArchivoProyecto()
        {
            this.tblArchivoProyecto_Materiales = new HashSet<tblArchivoProyecto_Materiales>();
        }
    
        public int IdArchivoProyecto { get; set; }
        [Display(Name = "Nombre de Proyecto")]
        public string NombreArchivo { get; set; }
        [Display(Name = "Tipo de Construcción")]
        public string TipoConstruccion { get; set; }
        //[DataType(DataType.Date)]
        [Required(AllowEmptyStrings =true)]
        public System.DateTime Fecha { get; set; }
        [Display(Name = "Precio Total")]
        public Nullable<decimal> PrecioTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArchivoProyecto_Materiales> tblArchivoProyecto_Materiales { get; set; }
    }
}
