//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWEB1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMateriales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMateriales()
        {
            this.tblArchivoProyecto_Materiales = new HashSet<tblArchivoProyecto_Materiales>();
        }
    
        public int IdMaterial { get; set; }
        [Display(Name = "Material")]
        public string NombreMaterial { get; set; }
        [Display(Name = "Precio por Unidad")]
        public decimal PrecioMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArchivoProyecto_Materiales> tblArchivoProyecto_Materiales { get; set; }
    }
}
